import Head from 'next/head';
import { css } from '@emotion/react';
import Image from 'next/image';
import { useState } from 'react';

const splashContainer = css`
  background: var(--color-orange);
  height: 100svh;
  display: flex;
  align-items: center;
  justify-content: center;
`;

export default function Home() {
  const [active, setActive] = useState('');
  setTimeout(() => {
    setActive('action');
  }, 3000);

  return (
    <>
      <Head>
        <title>Lunch Maps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div css={splashContainer} className={active}>
          <p>
            <Image src="./images/logo.svg" width={72} height={74} alt="" />
          </p>
        </div>
      </main>
    </>
  );
}
